import * as svg from '../svg';
import { SvgCardProps } from '../svg/SvgCardProps';

export const svgComponents: { [key: string]: React.FC<SvgCardProps> } = {
  C1: svg.Clubs1SvgComponent,
  C2: svg.Clubs2SvgComponent,
  C3: svg.Clubs3SvgComponent,
  C4: svg.Clubs4SvgComponent,
  C5: svg.Clubs5SvgComponent,
  C6: svg.Clubs6SvgComponent,
  C7: svg.Clubs7SvgComponent,
  C8: svg.Clubs8SvgComponent,
  C9: svg.Clubs9SvgComponent,
  C10: svg.Clubs10SvgComponent,
  C11: svg.ClubsJackSvgComponent,
  C12: svg.ClubsQueenSvgComponent,
  C13: svg.ClubsKingSvgComponent,

  D1: svg.Diamonds1SvgComponent,
  D2: svg.Diamonds2SvgComponent,
  D3: svg.Diamonds3SvgComponent,
  D4: svg.Diamonds4SvgComponent,
  D5: svg.Diamonds5SvgComponent,
  D6: svg.Diamonds6SvgComponent,
  D7: svg.Diamonds7SvgComponent,
  D8: svg.Diamonds8SvgComponent,
  D9: svg.Diamonds9SvgComponent,
  D10: svg.Diamonds10SvgComponent,
  D11: svg.DiamondsJackSvgComponent,
  D12: svg.DiamondsQueenSvgComponent,
  D13: svg.DiamondsKingSvgComponent,

  H1: svg.Hearts1SvgComponent,
  H2: svg.Hearts2SvgComponent,
  H3: svg.Hearts3SvgComponent,
  H4: svg.Hearts4SvgComponent,
  H5: svg.Hearts5SvgComponent,
  H6: svg.Hearts6SvgComponent,
  H7: svg.Hearts7SvgComponent,
  H8: svg.Hearts8SvgComponent,
  H9: svg.Hearts9SvgComponent,
  H10: svg.Hearts10SvgComponent,
  H11: svg.HeartsJackSvgComponent,
  H12: svg.HeartsQueenSvgComponent,
  H13: svg.HeartsKingSvgComponent,

  S1: svg.Spades1SvgComponent,
  S2: svg.Spades2SvgComponent,
  S3: svg.Spades3SvgComponent,
  S4: svg.Spades4SvgComponent,
  S5: svg.Spades5SvgComponent,
  S6: svg.Spades6SvgComponent,
  S7: svg.Spades7SvgComponent,
  S8: svg.Spades8SvgComponent,
  S9: svg.Spades9SvgComponent,
  S10: svg.Spades10SvgComponent,
  S11: svg.SpadesJackSvgComponent,
  S12: svg.SpadesQueenSvgComponent,
  S13: svg.SpadesKingSvgComponent,

  B1: svg.Back1SvgComponent,
  B2: svg.Back2SvgComponent,
};
